baseURL: https://jakebailey.dev/
languageCode: en-us
title: Jake Bailey
theme: github.com/adityatelange/hugo-PaperMod

params:
  env: production
  description: >
    Hi, I'm Jake.
    I'm a Senior Software Engineer at Microsoft, working on TypeScript.
    Here's where I put random stuff.

  homeInfoParams:
    title: "Hi, I'm Jake."
    content: >
      I'm a Senior Software Engineer at Microsoft, working on TypeScript.
      Here's where I put random stuff.

  socialIcons:
    - name: github
      url: 'https://github.com/jakebailey'
    - name: bluesky
      url: 'https://bsky.app/profile/jakebailey.dev'
    - name: mastodon
      url: 'https://fosstodon.org/@jakebailey'
    - name: twitter
      url: 'https://twitter.com/andhaveaniceday'
    - name: reddit
      url: 'https://www.reddit.com/user/Bake_Jailey'
    - name: ycombinator
      url: 'https://news.ycombinator.com/user?id=jakebailey'
    - name: linkedin
      url: 'https://linkedin.com/in/jakebbailey'
    - name: rss
      url: 'index.xml'

  showReadingTime: true
  showPostNavLinks: true
  showCodeCopyButtons: true
  showToc: true
  showFullTextInRSS: true
  showRssButtonInSectionTermList: true
  showWordCount: true
  comments: true

  schema:
    publisherType: Person

  extraSiteMap:
    - https://jakebailey.dev/esbuild-playground/
    - https://jakebailey.dev/hereby/
    - https://jakebailey.dev/dt-dashboard/

  mainSections:
    - posts

menu:
  main:
    - name: Projects
      url: /projects
      weight: 5
    - name: Archive
      url: /archives
      weight: 10
    - name: Search
      url: /search
      weight: 15

outputs:
  home:
    - HTML
    - RSS
    - JSON
